meta_product_name: "Handy Ladies"
meta_title: "HandyLadies - Make sure your home is the place you feel most safe."
meta_description: "Handy Ladies is a platform that connects female workers who are looking to expand their place in the market dominated by men.
This app will help women find other women to help with home repairs."
meta_image: "handyladies.jpg"
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
